name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * * *' # 每天的 UTC 00:00 触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "This job was triggered by a schedule."
